// Mocks generated by Mockito 5.4.6 from annotations
// in tv_program/test/tv_prog_app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:intl/intl.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_program/api/tv_prog_api.dart' as _i4;
import 'package:tv_program/models/channel.dart' as _i6;
import 'package:tv_program/models/program.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateFormat_0 extends _i1.SmartFake implements _i2.DateFormat {
  _FakeDateFormat_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProgram_1 extends _i1.SmartFake implements _i3.Program {
  _FakeProgram_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvProgApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvProgApi extends _i1.Mock implements _i4.TvProgApi {
  MockTvProgApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DateFormat get format => (super.noSuchMethod(
        Invocation.getter(#format),
        returnValue: _FakeDateFormat_0(
          this,
          Invocation.getter(#format),
        ),
      ) as _i2.DateFormat);

  @override
  _i5.Future<List<_i6.Channel>> fetchChannels(String? program) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChannels,
          [program],
        ),
        returnValue: _i5.Future<List<_i6.Channel>>.value(<_i6.Channel>[]),
      ) as _i5.Future<List<_i6.Channel>>);

  @override
  _i5.Future<List<_i3.Program>> fetchPrograms(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPrograms,
          [channelId],
        ),
        returnValue: _i5.Future<List<_i3.Program>>.value(<_i3.Program>[]),
      ) as _i5.Future<List<_i3.Program>>);

  @override
  _i5.Future<_i3.Program> fetchCurrentProgram(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentProgram,
          [channelId],
        ),
        returnValue: _i5.Future<_i3.Program>.value(_FakeProgram_1(
          this,
          Invocation.method(
            #fetchCurrentProgram,
            [channelId],
          ),
        )),
      ) as _i5.Future<_i3.Program>);

  @override
  _i5.Future<_i3.Program?> fetchTonightProgram(String? channelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTonightProgram,
          [channelId],
        ),
        returnValue: _i5.Future<_i3.Program?>.value(),
      ) as _i5.Future<_i3.Program?>);
}
